export function defineCustomTheme(monaco: any) {
  if (!monaco?.editor) return;
  monaco.editor.defineTheme("synscript-dark", {
    base: "vs-dark",
    inherit: true,
    rules: [
      { token: "keyword", foreground: "d0bcff" },
      { token: "keyword.control", foreground: "d0bcff" },
      { token: "string", foreground: "25C2A0" },
      { token: "string.value", foreground: "25C2A0" },
      { token: "number", foreground: "ffb786" },
      { token: "comment", foreground: "8c909f", fontStyle: "italic" },
      { token: "function", foreground: "adc6ff" },
      { token: "type", foreground: "7dd3fc" },
      { token: "type.identifier", foreground: "7dd3fc" },
      { token: "variable", foreground: "e1e2eb" },
      { token: "tag", foreground: "f472b6" },
      { token: "tag.html", foreground: "f472b6" },
      { token: "attribute.name", foreground: "adc6ff" },
      { token: "attribute.name.html", foreground: "adc6ff" },
      { token: "attribute.value", foreground: "25C2A0" },
      { token: "attribute.value.html", foreground: "25C2A0" },
      { token: "delimiter", foreground: "8c909f" },
      { token: "delimiter.html", foreground: "8c909f" },
      { token: "metatag", foreground: "8c909f" },
      { token: "metatag.html", foreground: "8c909f" },
      { token: "metatag.content.html", foreground: "25C2A0" },
      { token: "operator", foreground: "c9d1d9" },
      { token: "regexp", foreground: "ffb786" },
      { token: "annotation", foreground: "d0bcff" },
      { token: "constant", foreground: "ffb786" },
    ],
    colors: {
      "editor.background": "#0d1117",
      "editor.foreground": "#e1e2eb",
      "editor.lineHighlightBackground": "#00000000",
      "editorCursor.foreground": "#adc6ff",
      "editor.selectionBackground": "#3B82F640",
      "editor.selectionHighlightBackground": "#00000000",
      "editor.wordHighlightBackground": "#00000000",
      "editor.wordHighlightStrongBackground": "#00000000",
      "editorLineNumber.foreground": "#8c909f",
      "editorLineNumber.activeForeground": "#adc6ff",
      "editorIndentGuide.background": "#00000000",
      "editorIndentGuide.activeBackground": "#00000000",
      "editorBracketMatch.background": "#00000000",
      "editorBracketMatch.border": "#00000000",
      "minimap.background": "#0d1117",
      "editorGutter.background": "#0d1117",
      "editorWidget.background": "#161b22",
      "editorWidget.border": "#30363d",
      "editorSuggestWidget.background": "#161b22",
      "editorSuggestWidget.border": "#30363d",
      "editorSuggestWidget.selectedBackground": "#1d202680",
      "editorSuggestWidget.highlightForeground": "#adc6ff",
      "editorHoverWidget.background": "#161b22",
      "editorHoverWidget.border": "#30363d",
      "input.background": "#0d1117",
      "input.border": "#30363d",
      "input.foreground": "#e1e2eb",
      "scrollbarSlider.background": "#32353c60",
      "scrollbarSlider.hoverBackground": "#42475480",
      "scrollbarSlider.activeBackground": "#52576490",
    },
  });
}
